### ISSUE TITLE
Create Account for Expo and learn the basics #1

### ISSUE THREAD

**Issue by vvn1000** [CSAllenISD/2023-ISP-CafeProject#17]
Please follow the instructions https://docs.expo.dev/get-started/installation/ to get everything setup.

**Comment by saip9** [comment]
Make sure to install Node.js on Ubuntu because administrator privileges are required if installed on Mac, and we don't have access to those credentials.

**Comment by MustafaShihab1** [comment]
will do.

**Comment by saip9** [comment]
If anybody is confused between Expo and React Native, below is an explanation that explains the difference between these two:
Expo is very useful because we can build Android and iOS apps simultaneously with JS (JavaScript), saving time and effort. Also, it is a free and open-source platform that allows developers to quickly build apps with JavaScript and React Native. It provides a set of tools, libraries, and services that make it easier to get started with building a mobile app. React Native, on the other hand, is a framework for building mobile apps using React. Many developers around the world use these tools everyday. This makes it easer to seek support or research solutions online when faced with errors or bugs. 


Here are some links to some resources that could help potentially Software Developers code the application:

https://docs.expo.dev/tutorial/introduction/
https://www.youtube.com/watch?v=iQ_0Fd_N3Mk&t=950s
https://www.youtube.com/watch?v=0-S5a0eXPoc

**Comment by saip9** [comment]
- Marking issue as "Done" on Friday February 24 2023 

All of the team members have successfully registered on Expo and have begun the process of learning the programming languages and other aspects of mobile development.
