### ISSUE TITLE
Download Visual Studio Code and Android Studio

### ISSUE THREAD

**Issue by saip9** [CSAllenISD/2023-ISP-CafeProject#3]
Android Studio - For running andriod simulator to test the apps
Visual Studio Code - For writing code

**Comment by Fangedan** [comment]
Do we download them on our computers or phones?

**Comment by Fangedan** [comment]
Nevermind, they don't seem to exist in the app store :)

**Comment by saip9** [comment]
Install them on the computer

**Comment by vvn1000** [comment]
https://www.youtube.com/watch?v=09TeUXjzpKs

this dude did a video on making an app. its 3 hours long but you can skip around and figure out how to use xcode a little better.

**Comment by saip9** [comment]
You should use Visual Studio Code to write your code not XCode.

**Comment by Fangedan** [comment]
From what I'm hearing, Visual Studio code can be run on Windows and can make apps for IOS and Android, so that's what I'll primarily be using.

**Comment by MustafaShihab1** [comment]
I'm try to learn how to use Visual Studio.

**Comment by jakepodewils** [comment]
I have officialy started the process of downloading Visual Studio Code. First, make sure you access the website in order to download Visual Studio Code, at https://code.visualstudio.com/ and make sure to locate the blue "Download" button in the top right of the home page. Locate the ".deb" download button, where you will find Ubuntu (P.S. this only works when at the steam center on Ubuntu, or if you have Ubuntu at home). Once you hit the download button, a download mangager tab should appear towards the top right of your screen, and begin to download. Once it finishes downloading, click on the download manager where it says "open files" and open the application with the bottom selection, and it should say something along the lines of "software...". Once you click this, make sure to wait for it to open, as it does take quite a while. Once inside of the application, there should be a green download button, and the program should begin to download.
