### ISSUE TITLE
Discuss email from Student Nutition Manager/Director

### ISSUE THREAD

**Issue by Fangedan** [CSAllenISD/2023-ISP-CafeProject#54]
Kirsten Reitzammer has responded to our email proposing the use of PayPams in conjunction with our app:

Hi Andrew,
I received your e-mail from Ms. Oujout, our Concessions Manager at the district. My Assistant Director, Jeff and myself have reviewed your e-mail, as well as your business proposal. Although we appreciate the time and attention that was put in to your project, we cannot move forward with contacting PayPams to set up a pre-order application for a few different reasons. First and foremost, we are currently making a decision on whether or not we will continue to work with our current software company that operates our front of house, back of house and payments website due to some ongoing issues. Thus, there is strong possibility we will not be using this software moving forward. Secondly, regardless if we continued with our current software, they have conveyed to us that they do not have the capabilities to work with an outside application, previously, and most likely—if they created such a capability, it would be a sole-source, in which integration from other platforms would not be a possibility. There are other software companies we are looking at, currently, that could potentially lead us to the possibility of pre-orders in the future (that they are working on internally), but, this would be a learning curve for our staff and something that we would logistically need to work through as a department. Again, we appreciate all of the effort put forth on this project; but, a pre-order application with our current software and department operations is not a feasible option presently. Please let me know if you have additional questions or concerns.
Best,

Now, we should discuss our response to continue with our project. I propose that we slightly modify it so that students can inform the cafeteria staff of their order through our app, but leave the payment to the school ID's and current system. Through the app, a QR code will be provided to verify the student's identity for the order, but the student will have to use their ID to pay for the order, so that we do not need to be involved with PayPams. What do y'all think?

**Comment by saip9** [comment]
- Adding all team members as "Assignees"
- Adding label as "Help Wanted"
- Adding priority as "Must Have" 

@Fangedan,
I mostly agree with your solution that we should a design QR code system for students to verify their identity without taking payment. To achieve this, we have to have a different account system for cafeteria and administrative officials. When students order their food. it should then automatically "transfer" or "reflect" the order on their end. My only concern is how would the order total from our system be reflected on their payment portal? The only way to combat this problem is to have the cafeteria workers scan the products and to populate the bill. But, it would take very long and careful coordination everyday for this to happen. So, let me know if you have any questions or other ideas. It is critical for us to think through the whole process understanding the both the pros and cons at each stage, so we don't put unnecessary strain or work on either the students or cafeteria workers.

**Comment by Fangedan** [comment]
Sai,

Thank you for your concern on the QR code issue. I think an area of miscommunication you might have is that you think that we are accounting for the total price of the student's order. As with our new proposed plan, we are removing any payment aspects of the application, which includes the student's payment portal. This would allow the cafeteria staff to regularly scan the student's items into their registers and let the students pay with their ID's as usual. As for monetary issues, the only thing we would provide students is the price for each item and the total amount of their purchase, which is relatively easy as everything has a set price.
